# Generated by Django 5.2.8 on 2025-11-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(default='Binance', max_length=50, verbose_name='Биржа')),
                ('symbol', models.CharField(max_length=20, verbose_name='Пара (например, BTCUSDT)')),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=5, verbose_name='Направление')),
                ('leverage', models.PositiveIntegerField(default=1, verbose_name='Плечо')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Объём (контракты/монеты)')),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Цена входа')),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Stop-loss')),
                ('take_profit_1', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='TP1')),
                ('take_profit_2', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='TP2')),
                ('take_profit_3', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='TP3')),
                ('status', models.CharField(choices=[('OPEN', 'Открыта'), ('CLOSED', 'Закрыта')], default='OPEN', max_length=6, verbose_name='Статус')),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Результат (USDT)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыто')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-created_at'],
            },
        ),
    ]
